### PR TITLE
add back dbt-snowflake hacks

### PR DESCRIPTION
**Pull request by kwigley**
### Description

resolves error when install dbt-snowflake formula, this installs `snowflake-connector-python` without `pyarrow` as a build dependency. We don't use the `pandas` functionality of `snowflake-connector-python` so this doesn't affect functionality.

```
==> /usr/local/Cellar/dbt-snowflake/1.0.1/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dbt-snowflake--snowflake-connector-python-20220421-26995-6jqz9t/snowflake-connector-python-2.7.6
Last 15 lines from /Users/kwigley/Library/Logs/Homebrew/dbt-snowflake/47.pip:
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /usr/local/Cellar/dbt-snowflake/1.0.1/libexec/bin/python3.9 /private/tmp/pip-standalone-pip-xkcpdqdd/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/tmp/pip-build-env-13g6mahf/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel cython 'pyarrow>=6.0.0,<6.1.0'
  cwd: [inherit]
  Installing build dependencies: finished with status 'error'
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

### Checklist

- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR

### CODE REVIEW

**Comment by leahwicz** [comment]
@kwigley this was the error I saw when trying last week

```
Last 15 lines from /Users/leahwicz/Library/Logs/Homebrew/dbt-snowflake@1.1.0-rc1/47.pip:
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /usr/local/Cellar/dbt-snowflake@1.1.0-rc1/1.1.0rc1_1/libexec/bin/python3.9 /private/tmp/pip-standalone-pip-oq9v3h_o/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/tmp/pip-build-env-h25p443h/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.6.0' wheel cython 'pyarrow>=6.0.0,<6.1.0'
  cwd: [inherit]
  Installing build dependencies: finished with status 'error'
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/dbt-labs/homebrew-dbt/issues

**Comment by leahwicz** [comment]
It looks the same as you have there so 🤞 this works. Thanks for the fix!

**Review by leahwicz — APPROVED** [review]

**Comment by leahwicz** [comment]
We also were doing different install steps for postgres previously. Not sure if we don't need to do these now either
https://github.com/dbt-labs/homebrew-dbt/pull/79/commits/4cfbdf81ee57e829b82a2c2ba037fe08ce45ac45

**Comment by kwigley** [comment]
@leahwicz good call, I added this back

**Pull request merged**
